//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 BM.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_FORMVIEW_SERVICE_SEARCH     101
#define IDD_PROPPAGE_PRODUCTINFO        107
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE_STATUS_OPERATION 122
#define IDS_STATUS_PANE2                123
#define IDS_STATUS_PANE_CUR_TIME        123
#define IDS_STATUS_PANE_DEAL_NEW_TIME   124
#define IDS_STATUS_PANE_USER            125
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define ID_TOOLS_OPTIONS                220
#define ID_VIEW_CAPTION_BAR             221
#define IDB_INFO                        230
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDD_DIALOG_DBCONF               310
#define IDD_DLG_DBCONF                  310
#define IDD_DIALOG_DBNEW                311
#define IDD_DLG_DBNEW                   311
#define IDD_DIALOG_LOGIN                312
#define IDD_DLG_LOGIN                   312
#define IDD_DIALOG_PWDEDIT              313
#define IDD_DLG_PWDEDIT                 313
#define IDB_BITMAP_QATLARGE             318
#define IDB_BITMAP_QATSMALL             320
#define IDB_BITMAP_MAINBMP              322
#define IDI_ICON_BMMAIN                 323
#define IDR_MAINFRM                     324
#define IDI_ICON1                       325
#define IDB_BITMAP_SYSTEMSETUPSMALL     327
#define IDB_BITMAP_SSLARGE              329
#define IDB_BITMAP_EMM                  331
#define IDB_BITMAP_CUSTOMINFO           332
#define IDB_BITMAP_STOCK                333
#define IDB_BITMAP_SERVICE              334
#define IDB_BITMAP2                     335
#define IDB_BITMAP_PROGRESS             335
#define IDD_DLG_MAINVIEW                336
#define IDD_DLG_EMPLOYEEINFOVIEW        337
#define IDD_PROPPAGE_EMPINFO            338
#define IDD_PROPPAGE_CUSTOMINFO         339
#define IDR_MENU_OPERATION              339
#define IDM_EMP_EX_OPERATION            339
#define IDR_MENU_OPERATION1             340
#define IDD_PROPPAGE_EMPINFO1           340
#define IDD_PROPPAGE_EMPINFO_EX         340
#define IDM_PROD_IM_OPERATION           340
#define IDR_MENU_OPERATION2             341
#define IDD_PROPPAGE_PRODUCTINFO1       341
#define IDD_PROPPAGE_PRODUCTINFO_EX     341
#define IDM_EMP_IMPORT_OPERATION        341
#define IDD_PROPPAGE_CUSTOMINFO1        342
#define IDD_PROPPAGE_CUSTOMINFO_EX      342
#define IDD_DLG_SYSPOSTION              343
#define IDD_PROPPAGE_MTSET              346
#define IDD_PROPPAGE_FCTSET             347
#define IDD_DLG_CTMINFO                 348
#define IDD_DLG_CTM_NEW                 349
#define IDD_DLG_CTM_EDIT                350
#define IDD_DLG_STOREINFO               351
#define IDD_DLG_STOREADD                352
#define IDD_DLG_STORE_OUT               353
#define IDD_DLG_STORE_HISTORY           354
#define IDD_DLG_SERVICE_REG             356
#define IDD_DLG_SERVICE_MODIFY          357
#define IDD_FORMVIEW_DEAL_LIST          359
#define IDR_MENU_ORDER_OPERATION        359
#define IDD_PROPPAGE_ORDER_CONTENT      360
#define IDD_DLG_ORDER_CONTENT           360
#define IDD_FORMVIEW_DEAL_INCOMPLETED   362
#define IDD_DLG_ORDER_EDIT              363
#define IDD_FORMVIEW_PERFORMANCE_MG     364
#define IDD_DLG_EMP_PERFORMANCE_SEARCH  365
#define IDD_DLG_DEDUCT_SET              366
#define IDB_BITMAP_MAINFORMVIEW         367
#define IDD_DLG_EMP_NEW                 368
#define IDD_DLG_EMP_EDIT                369
#define IDD_DLG_NOTE_PUBLIC             370
#define IDD_DLG_MT_NOTE_NEW             372
#define IDD_DLG_MT_NOTE_EDIT            373
#define IDD_DLG_FACTORY_NEW             374
#define IDD_DLG_FACTORY_EDIT            375
#define IDD_DLG_SERV_SEARCH             377
#define IDD_DLG_EMPINFO_SEARCH          378
#define IDD_DLG_STORE_ALERT_SET         383
#define IDD_DLG_POS_ADD                 385
#define IDD_DLG_POS_EDIT                386
#define IDM_PROD_EX_OPERATION           388
#define IDM_CTM_EX_OPERATION            389
#define IDM_CTM_IM_OPERATION            390
#define IDM_ORDER_INCOMPLETE_OPERATION  391
#define IDM_EMP_PERFORMANCE             394
#define IDM_SYSPOSTION_MG               395
#define IDC_BUTTON_DBNEW                1000
#define IDC_COMBO1                      1001
#define IDC_COMBO_DB_NAME               1001
#define IDC_COMBO_POS_NAME              1001
#define IDC_COMBO2                      1002
#define IDC_COMBO_IP                    1002
#define IDC_BUTTON_REFRESH              1003
#define IDC_COMBO3                      1003
#define IDC_COMBO_LOGIN_USERNAME        1003
#define IDC_EDIT1                       1004
#define IDC_COMBO_PORT                  1004
#define IDC_EDIT2                       1005
#define IDC_BUTTON_REGISTER             1005
#define IDC_EDIT_PSWNEW                 1005
#define IDC_EDIT3                       1006
#define IDC_CHECK_REM_PSW               1006
#define IDC_EDIT_PSWNEW_CONFIRM         1006
#define IDC_EDIT4                       1007
#define IDC_BUTTON_PWDEDIT              1007
#define IDC_EDIT_DB_NAME                1007
#define IDC_COMBO_SERVERNAME            1008
#define IDC_EDIT_NO_INNER_MODIFY_DESIGN 1008
#define IDC_EDIT5                       1008
#define IDC_EDIT_MAIN_PRODUCT_FctNew    1008
#define IDC_DATETIMEPICKER1             1009
#define IDC_EDIT_PHONE                  1009
#define IDC_EDIT_HAS_INNER_MODIFY_DESIGN 1009
#define IDC_DATETIME_DEAL_NEW           1009
#define IDC_EDIT6                       1009
#define IDC_EDIT_PS_FctNew              1009
#define IDC_DATETIMEPICKER_FIRST_DEAL   1009
#define IDC_RICHEDIT2_NOTIFY            1010
#define IDC_DATE_LAST                   1010
#define IDC_DATETIME_DEADLINE           1010
#define IDC_EDIT_ADDR                   1010
#define IDC_DATETIME_END                1010
#define IDC_EDIT_EXACT_TEST_PERSON      1010
#define IDC_DATETIMEPICKER_LATE_DEAL    1010
#define IDC_LIST1                       1011
#define IDC_LIST_NOTIFY                 1011
#define IDC_EDIT_EMP_ADDR               1011
#define IDC_LIST_FCTORY_INFO            1011
#define IDC_EDIT_SERV_CONTENT           1012
#define IDC_RICHEDIT2_NOTIFY2           1012
#define IDC_EDIT_EMP_PHONE              1012
#define IDC_EDIT_POSTION                1013
#define IDC_BTN_DATAIMPORT              1014
#define IDC_EDIT_SERV_NM                1014
#define IDC_EDIT_EMP_PS                 1014
#define IDC_BTN_SUBMIT                  1015
#define IDC_EDIT_SERV_PHONE             1015
#define IDC_EDIT_CHARGE                 1016
#define IDC_SPLIT_OPERATION             1017
#define IDC_EDIT_SERVTYPE               1017
#define IDC_EDIT_SERV_TYPE              1017
#define IDC_LIST_CTMINFO                1019
#define IDC_BTN_PRODINFOIMPORT          1020
#define IDC_BTN_DATASUBMIT              1021
#define IDC_SPLIT_OPER2                 1023
#define IDC_LIST_PROD                   1024
#define IDC_BTN_EMPIMPORT               1025
#define IDC_SPLIT_OPERATION2            1026
#define IDC_LIST_EMP                    1027
#define IDC_BTN_DATAEXPORT              1028
#define IDC_BTN_EXPORT                  1029
#define IDC_BTN_FIND_ALLCTM             1029
#define IDC_BTN_EMPSEARCH               1030
#define IDC_BTN_EMPEXPORT               1031
#define IDC_BTN_PRODSEARCH              1032
#define IDC_BTN_ADD                     1033
#define IDC_BTN_EDIT                    1034
#define IDC_BTN_DELETE                  1035
#define IDC_BTN_DEL                     1035
#define IDC_LIST_SYSPOSTION             1036
#define IDC_BTN_FIND_MORE               1036
#define IDC_ET_PSW                      1038
#define IDC_BTN_ADDPOS                  1039
#define IDC_BTN_SAVE_POS                1039
#define IDC_ET_POSNO                    1040
#define IDC_ET_EMPNM                    1042
#define IDC_ET_EMPPS                    1043
#define IDC_TREE_PSOAUTHORITY           1044
#define IDC_BTN_NEW                     1053
#define IDC_BTN_MTEDIT                  1054
#define IDC_BTN_MTDELETE                1055
#define IDC_TREE_MTSET                  1056
#define IDC_BTN_REFRESH                 1056
#define IDC_BTN_FCTNEW                  1057
#define IDC_BTN_FCTEDIT                 1058
#define IDC_BTN_FCTDELETE               1059
#define IDC_TREE_FCT                    1060
#define IDC_EDIT_PHONENO                1064
#define IDC_EDIT_CTMNM                  1065
#define IDC_EDIT_CTMCALL                1066
#define IDC_EDIT_CTMNO                  1067
#define IDC_COMBO_CTMSEX                1068
#define IDC_EDIT_TIMES                  1069
#define IDC_BTN_CANCLE                  1071
#define IDC_EDIT_PS                     1072
#define IDC_DATE_FIRST                  1075
#define IDC_BTN_SAVE                    1076
#define IDC_EDIT_PRICE                  1077
#define IDC_BTN_SEARCH                  1078
#define IDC_BTN_STOREADD                1079
#define IDC_BTN_EMP_NEW                 1079
#define IDC_BTN_SEARCH_COMM             1079
#define IDC_BTN_SEARCH_VIA_DATE         1079
#define IDC_BTN_STOREOUT                1080
#define IDC_BTN_EMP_EDIT                1080
#define IDC_LIST_STOREINFO              1081
#define IDC_BTN_EMP_DEL                 1081
#define IDC_EDIT_IDENTIFY               1084
#define IDC_EDIT_NUMADD                 1085
#define IDC_EDIT_NUMALERT               1086
#define IDC_BTN_STORE_OUT               1087
#define IDC_EDIT_NUM_OUT                1088
#define IDC_LIST_STORE_HISTORY          1089
#define IDC_STATIC_PICTURE              1091
#define IDC_BTN_ACCESSORY_CHOOSE        1092
#define IDC_BTN_ORDER_ALL_EMP           1092
#define IDC_BTN_SEACH                   1092
#define IDC_BTN_PUBLIC                  1092
#define IDC_BTN_NOTE_NEW                1092
#define IDC_BTN_SEARCH_BY_KEYWORD       1092
#define IDC_EDIT_KEYWORD                1093
#define IDC_BTN_CANCEL                  1093
#define IDC_BTN_ACCESSORY_START_UPLOAD  1093
#define IDC_BTN_PERFORMANCE_DEDUCT_SET  1093
#define IDC_BTN_QUIT                    1093
#define IDC_BTN_SEARCH_ALL              1093
#define IDC_DATETIME_START              1094
#define IDC_COMBO_TIMECHOOSE            1095
#define IDC_LIST_SERVICE                1096
#define IDC_BTN_DEDUCT_TOTAL            1096
#define IDC_DATETIME_REQ                1097
#define IDC_DATETIME_DELAY              1098
#define IDC_EDIT_SERV_NO                1099
#define IDC_COMBO_CTM_TYPE              1100
#define IDC_EDIT_CTM_NM                 1101
#define IDC_EDIT_CLIENT_NM              1102
#define IDC_COMBO_CTM_SEX               1103
#define IDC_COMBO_PROG                  1104
#define IDC_COMBO_SERV_TYPE             1105
#define IDC_LIST_DEAL                   1106
#define IDC_EDIT_ORDER_NO               1107
#define IDC_DATETIME_ORDER_ACCEPT       1108
#define IDC_DATETIME_ORDER_FINISHED     1109
#define IDC_EDIT_CHARGE_NM              1110
#define IDC_EDIT_BASEINFO_PS            1111
#define IDC_COMBO_CTM_FROM              1112
#define IDC_EDIT_INTR_NM                1113
#define IDC_EDIT_INTR_PHONE             1114
#define IDC_STATIC_INTR_NAME            1115
#define IDC_STATIC_INTR_PHONE           1116
#define IDC_STATIC_SERV_PERSON          1117
#define IDC_EDIT_SERV_PERSON            1118
#define IDC_COMBO_BUSINESS_PROG         1119
#define IDC_DATETIME_FIRST_TEST         1120
#define IDC_COMBO_EARLY_STAGE_TYPE      1121
#define IDC_COMBO_ORDER_DISCUSS_TYPE    1122
#define IDC_STATIC_EMP_DONE             1123
#define IDC_EDIT_EMP_NAME               1124
#define IDC_DATETIME_OUT_ORDER_BOOK     1125
#define IDC_EDIT_CTM_CALL               1126
#define IDC_EDIT_CTM_NAME               1127
#define IDC_EDIT_CTM_PHONE              1128
#define IDC_EDIT_CTM_ADDR               1129
#define IDC_EDIT_CTM_PS                 1130
#define IDC_EDIT_CONTRACT_NO            1131
#define IDC_EDIT_DEAL_DISCUSS_PERSON1   1132
#define IDC_EDIT_PERSON_OUT_ORDER       1133
#define IDC_EDIT_DEAL_DISCUSS_PERSON2   1134
#define IDC_EDIT_EARLY_STAGE_MODIFY_PERSON 1135
#define IDC_EDIT_PERSION_FIRST_DESIGN   1136
#define IDC_EDIT_PERSON_FIRST_DESIGN    1136
#define IDC_EDIT_PERSON_BUDGET          1137
#define IDC_EDIT_EXACT_MEASURE_PERSON   1138
#define IDC_DATETIME_FINAL_SCHEME       1141
#define IDC_DATETIME_BOOK               1142
#define IDC_EDIT_CONTRACT_TOTAL_PRICE   1143
#define IDC_EDIT_MONEY_ALREADY_TAKE     1144
#define IDC_LIST_ORDER_INCOMPLETED_PROG 1147
#define IDC_EDIT_ACCESSORY_FILE_PATH    1148
#define IDC_COMBO_PAY_DEAL_CHOOSE       1149
#define IDC_EDIT_UPLOAD_STATUS          1150
#define IDC_EDIT_FCTORY_CHOOSE          1151
#define IDC_BTN_FCTORY_CHOOSE           1152
#define IDC_PROGRESS_STATUS             1153
#define IDC_EDIT_INSTALL_PERSON         1154
#define IDC_EDIT_INSTALL_PROBLEMS       1155
#define IDC_DATETIME_INSTALL_BOOK       1156
#define IDC_BTN_ACCESSORY_DEL           1157
#define IDC_BTN_ACCESSORY_DOWNLOAD      1158
#define IDC_LIST_PERFORMANCE            1159
#define IDC_RADIO_SEARCH                1160
#define IDC_RADIO2                      1161
#define IDC_EDIT_EMP                    1161
#define IDC_RADIO3                      1162
#define IDC_EDIT_MEASURE                1162
#define IDC_RADIO4                      1163
#define IDC_EDIT_DECORATE_COMPANY       1163
#define IDC_EDIT_DISCUSS_DEAL_PERSON    1164
#define IDC_EDIT_EMP_NO                 1165
#define IDC_EDIT_PERSON_PUBLIC          1166
#define IDC_EDIT_TITLE                  1167
#define IDC_EDIT_CONTENT                1168
#define IDC_SPLIT_ADDR_ADD              1169
#define IDC_EDIT_EMP_POS                1169
#define IDC_COMBO_LOGIN_ADDR            1170
#define IDC_COMBO_LOGIN_POS             1171
#define IDC_EDIT_LOGIN_PSW              1172
#define IDC_TREE_MATERIAL               1173
#define IDC_EDIT_LOGIN_PSW2             1173
#define IDC_EDIT_STATUS                 1173
#define IDC_BTN_NOTE_SAVE               1174
#define IDC_RADIO1                      1175
#define IDC_RADIO_CTM_NAME              1175
#define IDC_RADIO_CHARGE_MAN            1175
#define IDC_RADIO_SERV_DATE             1176
#define IDC_BTN_GIVEUP                  1176
#define IDC_RADIO_NAME_CTM              1176
#define IDC_RADIO5                      1177
#define IDC_RADIO_ADDR                  1177
#define IDC_RADIO6                      1178
#define IDC_RADIO_NUM                   1178
#define IDC_RADIO7                      1179
#define IDC_RADIO_POS                   1179
#define IDC_RADIO_KEY                   1180
#define IDC_RADIO_NAME                  1180
#define IDC_BTN_LOGIN_CONTINUE          1181
#define IDC_BTN_LOGIN                   1182
#define IDC_BTN_GO_BACK                 1183
#define IDC_STATIC_STATUS               1184
#define IDC_EDIT_PARENT_NODE            1187
#define IDC_EDIT_NODE_NEW               1188
#define IDC_STATIC_TIPS                 1189
#define IDC_STATIC_TIME_TAKE            1193
#define IDC_EDIT_NODE_ORG               1194
#define IDC_EDIT_NOTE_NAME_NEW          1195
#define IDC_STATIC_TIP                  1196
#define IDC_EDIT_KEY_WORD               1199
#define IDC_BTN_SEARCHALL               1200
#define IDC_EDIT_NAME_FCT               1201
#define IDC_EDIT_ADDR_FCT               1202
#define IDC_EDIT_CONTACT_PERSON_FCT     1203
#define IDC_EDIT_PHONE_FCT              1204
#define IDC_EDIT_MAIN_PRODUCT_FCT       1205
#define IDC_EDIT_PS_FCT                 1206
#define IDC_EDIT_NAME_FCTORY_FctNew     1207
#define IDC_EDIT_ADDR_FCTORY_FctNew     1208
#define IDC_EDIT_CONTACTS_FctNew        1209
#define IDC_EDIT_PHONE_FctNew           1210
#define IDC_BTN_ALERT_SET               1212
#define IDC_EDIT_GOODS_NAME             1214
#define IDC_EDIT_GOOS_ALERT_NUM         1215
#define IDC_BTN_FIND_ALL                1216
#define IDC_BTN_DEL_HISTORY             1217
#define IDC_BTN_FINDALL                 1218
#define IDC_EDIT_PERDON_FIRST_TEST      1219
#define IDC_STATIC_UPLOAD_STATUS        1220
#define IDC_BTN_ACCESSORY_CHECK         1221
#define IDC_BTN_FILE_UPLOAD             1222
#define IDC_PROGRESS_DOWNLOAD           1222
#define IDC_STATIC_DLSTATUS             1223
#define IDC_EDIT_PERSON_FIRST_TEST      1225
#define IDC_BTN_CANCAL                  1227
#define IDC_BTN_SEARCH_KEYWORDS         1227
#define IDC_BTN_SEARCH_ALL_DEAL         1230
#define IDC_STATIC_CHOICE               1231
#define IDC_STATIC_KEYWORD              1232
#define IDC_EDIT_NAME_CONFIRM           1232
#define IDC_EDIT_NAME_CONFIRM2          1233
#define IDC_EDIT_PASSWORD               1234
#define IDC_BTN_FIND_DEAL_INCOMPLETE    1235
#define IDC_EDIT_KEYKORD                1237
#define IDC_SPLIT_DALIY_OPERATION       1238
#define IDC_SPLIT                       1239
#define IDC_ET_EMP_PASSWORD             1240
#define IDC_ET_PASSWORD_CONFIRM         1241
#define IDC_CHECK_DEAL_NEW              1242
#define IDC_CHECK_FIND_DEAL             1243
#define IDC_CHECK_UPLOAD_FILE           1244
#define IDC_CHECK_DEL_FILE              1245
#define IDC_CHECK_EDIT_DEAL_INCOMPLETE  1246
#define IDC_CHECK_EDIT_DEAL             1247
#define IDC_CHECK_DEL_DEAL              1248
#define IDC_CHECK_DOWNLOAD_FILE         1249
#define IDC_CHECK_FIND_DEAL_INCOMPLETE  1250
#define IDC_CHECK_FIND_STORE            1251
#define IDC_CHECK_ALERT_SET             1252
#define IDC_CHECK_STORE_ADD             1253
#define IDC_CHECK_STORE_OUT             1254
#define IDC_CHECK_HISTORY_FIND          1255
#define IDC_CHECK_DEL_HISTORY           1256
#define IDC_CHECK_FIND_EMP              1257
#define IDC_CHECK_EMP_NEW               1258
#define IDC_CHECK_FIND_EMP_EMPLOYEE     1259
#define IDC_CHECK_NOTE_PUBLIC           1259
#define IDC_CHECK_FIND_CTM              1260
#define IDC_CHECK_CTM_NEW               1261
#define IDC_CHECK_EDIT_CTM              1262
#define IDC_CHECK_DEL_CTM               1263
#define IDC_CHECK_POS_ADD               1264
#define IDC_CHECK_FIND_POS              1265
#define IDC_CHECK_DEL_POS               1266
#define IDC_CHECK_EDIT_POS              1267
#define IDC_CHECK_PROD_IM               1268
#define IDC_CHECK_PROD_EX               1269
#define IDC_CHECK_CTM_IM                1270
#define IDC_CHECK_CTM_EX                1271
#define IDC_CHECK_EMP_IM                1272
#define IDC_CHECK_EMP_EX                1273
#define IDC_CHECK_MT_FIND               1274
#define IDC_CHECK_NODE_NEW              1275
#define IDC_CHECK_NODE_EDIT             1276
#define IDC_CHECK_DEL_NODE              1277
#define IDC_CHECK_FIND_FCT              1278
#define IDC_CHECK_FCT_NEW               1279
#define IDC_CHECK_EDIT_FCT              1280
#define IDC_CHECK_DEL_FCT               1281
#define IDC_CHECK_EDIT_EMP              1282
#define IDC_CHECK_DEL_EMP               1283
#define IDC_CHECK_FIND_EMP_PERFERENCE   1284
#define IDC_CHECK_NOTE_DEL              1285
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_BUTTON2                      32772
#define ID_BUTTON_BACKOFF               32773
#define ID_BUTTON_GOFORWARD             32774
#define ID_BUTTON_RELOGIN               32775
#define ID_BUTTON_HOME                  32776
#define ID_BUTTON_DATAIMPORT            32777
#define ID_BUTTON_DATAEXPORT            32778
#define ID_BUTTON_SYSYTEMPOSTION        32779
#define ID_BUTTON_MATERIALANDFACTORY    32780
#define ID_BUTTON_EMPLOYEEINFO          32781
#define ID_BUTTON8_PERORMENCEMG         32782
#define ID_BUTTON_CUSTOMINFO            32783
#define ID_BUTTON_STOCKINFO             32784
#define ID_BUTTON_HISTORY               32785
#define ID_BUTTON_ALERTSETUP            32786
#define ID_BUTTON_DEALLIST              32787
#define ID_BUTTON_DEALNEW               32788
#define ID_BUTTON_DEALTRACE             32789
#define ID_BUTTON_SERVMG                32790
#define ID_BUTTON_SERVREG               32791
#define ID_BTN_DATAIMPORT               32792
#define ID_32793                        32793
#define ID_32794                        32794
#define ID_32795                        32795
#define ID_32796                        32796
#define ID_32797                        32797
#define ID_32799                        32799
#define ID_32800                        32800
#define ID_32801                        32801
#define ID_32802                        32802
#define ID_32803                        32803
#define ID_32804                        32804
#define ID_32805                        32805
#define ID_32806                        32806
#define ID_32807                        32807
#define ID_32808                        32808
#define ID_32809                        32809
#define ID_32810                        32810
#define ID_32811                        32811
#define ID_32812                        32812
#define ID_32813                        32813
#define ID_32814                        32814
#define ID_BTN_PERFORMENCEMG            32815
#define ID_32816                        32816
#define ID_32819                        32819
#define ID_CANCEL_CHOOSE_EMPINFOEX      32820
#define ID_DEL_EMP_EX                   32821
#define ID_CLEAR_ALL                    32822
#define ID_CHOOSE_ALL                   32823
#define ID_REVERSE_CHOOSE               32824
#define ID_CANCEL_CHOOSE                32825
#define ID_DEL                          32826
#define ID_CLEAR                        32827
#define ID_32828                        32828
#define ID_32829                        32829
#define ID_32830                        32830
#define ID_32831                        32831
#define ID_32832                        32832
#define ID__CHOOSE_ALL                  32833
#define ID_CHOOSE_NONE                  32834
#define ID_DEL_FROM_LIST                32835
#define ID_CLEAR_LIST                   32836
#define ID_32837                        32837
#define ID_32838                        32838
#define ID_32839                        32839
#define ID_32840                        32840
#define ID_32841                        32841
#define ID_CHOOSE_ALLL                  32842
#define ID_32843                        32843
#define ID_32844                        32844
#define ID_32845                        32845
#define ID_32846                        32846
#define ID_32847                        32847
#define ID_32848                        32848
#define ID_32849                        32849
#define ID_32850                        32850
#define ID_32851                        32851
#define ID_32852                        32852
#define ID_32853                        32853
#define ID_32854                        32854
#define ID_32855                        32855
#define ID_32856                        32856
#define ID_32857                        32857
#define ID_32858                        32858
#define ID_32859                        32859
#define ID_32860                        32860
#define ID_32861                        32861
#define ID_CLEAR_CUR_LIST               32862
#define ID_DEDUCT_SET                   32863
#define ID_ADD_ALL_DEDUCT               32864
#define ID_GET_DEDUCT                   32865
#define ID_32866                        32866
#define ID_32867                        32867
#define ID_32868                        32868
#define ID_32869                        32869
#define ID_32870                        32870
#define ID_DEL_ALLL                     32871

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        396
#define _APS_NEXT_COMMAND_VALUE         32872
#define _APS_NEXT_CONTROL_VALUE         1285
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
